### ISSUE TITLE
Optional pipeline steps: enabled=false boolean

### ISSUE THREAD

**Issue by karlkfi** [kptdev/kpt#2306]
I want to be able to ship kpt packages with optional features, but kpt doesn't have any conditional code blocks. 

One way to satisfy this requirement would be to add an `enabled` boolean to the pipeline step syntax in kpt v1. This would allow kptfiles to include steps that are disabled by default, allowing users to enable them with a one-line change.

An optional additional enhancement would be a CLI command for toggling steps by name:
```
kpt pipeline step enable "step-name"
```

**Comment by bgrant0607** [comment]
Sounds useful.

I wanted something similar for kustomize at some point.

**Comment by karlkfi** [comment]
Hypothetical example:

Kptfile:
```
pipeline:
  mutators:
  - image: gke-security-group
    configMap:
      domain: environblueprint.joonix.net
      parent: gke-security-groups
      create: true
      groups:
      - group1
      - group2
    enabled: false
```

This example would call a function to set the `spec.authenticatorGroupsConfig.securityGroup` on any `ContainerCluster` in the package, and make the group in Google Workspaces if it didn't already exist, but would be disabled by default, because not all users of the GKE clusters have a Google Workspace or Cloud Identity subscription.

This would allow reducing the dependencies of the package by default and making groups an optional dependency.
