### ISSUE TITLE
"error: yaml: did not find expected node content" attempting to set value starting with ","

### ISSUE THREAD

**Issue by taisph** [kptdev/kpt#2337]
Run `kpt cfg set . foo ",bar"`

### Expected behavior

```
./
set 1 field(s) of setter "foo" to value ",bar"
```

### Actual behavior

```
./
error: yaml: did not find expected node content
```

### Information

kpt version 0.39.3

### Steps to reproduce the behavior

Files used in test:

test.yaml:
```
foo: "bar" # {"$kpt-set":"foo"}
```

Kptfile:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: tmp
packageMetadata:
  shortDescription: sample description
openAPI:
  definitions:
    io.k8s.cli.setters.foo:
      x-k8s-cli:
        setter:
          name: foo
          value: 'bar'
```
