### ISSUE TITLE
New Porch installation: via ConfigSync `RootSync`

### ISSUE THREAD

**Issue by yuwenma** [kptdev/kpt#3556]
### Goal
To better align with the OSS ConfigSync, users can install Porch by applying a RootSync object. .

### UI
Users can write the following RootSync object and let it install Porch.
```yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: porch
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/GoogleContainerTools/porch/installation
    branch: v0.0.9
    auth: none
```
```bash
kubectl apply -f rootsync.yaml
```
### Porch support
Currently we store the porch artifacts in the corresponding release tag. e.g. 
git tag [porch/v0.0.9](https://github.com/GoogleContainerTools/kpt/tree/porch/v0.0.9/porch/deployments)
git tag [porch/v0.0.8](https://github.com/GoogleContainerTools/kpt/tree/porch/v0.0.8/porch/deployments)
git tag [porch/v0.0.7](https://github.com/GoogleContainerTools/kpt/tree/porch/v0.0.7/porch/deployments)

The deployment artifacts are allocated in 
- `porch/deployments/porch`  (Use image tag `latest`)
- `porch/controllers/config/crd/bases` (For CRD only)
- `porch/controllers/config/rbac` (for RBAC)

To support installing porch via ConfigSync, we need to 
- Add the porch artifacts in a centralized place
- Have the Deployment images use specific release version.
- Avoid having `.status` in the resources (current CRD object contains an empty `status` which is blocked by ConfigSync)
