### ISSUE TITLE
set-image sets conversion for web hook in CRD resource even if no web hook is setup

### ISSUE THREAD

**Issue by henderiw** [kptdev/kpt#3560]
### Expected behavior
Was asked by John to create an Issue
No conversion is added in CRD resource. The consequence is that by applying this CRD onto the cluster fails

```
  conversion:
    webhook:
      clientConfig:
        service:
          namespace: ndd-system
```

### Actual behavior

when set-namespace is used the following lines are added to the CRD resource

```
  conversion:
    webhook:
      clientConfig:
        service:
          namespace: ndd-system
```

### Information

the following lines on a Kpt Package that has a CRD resource

    - image: gcr.io/kpt-fn/set-namespace:v0.4.1
      configMap:
        namespace: xxx

### Steps to reproduce the behavior
