### ISSUE TITLE
Porch: Unable to have two git repos with same URL and different directories

### ISSUE THREAD

**Issue by LiptonB** [kptdev/kpt#3601]
### Expected behavior
I would like to store multiple groups of configs in the same git repository. I thought I might be able to do so by creating multiple porch Repositories pointing to the same git repo. So I have the following repositories with the same `repo` URL but different `directory` values:
```
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: repo1
  namespace: default
spec:
  content: Package
  deployment: true
  description: Repo1
  git:
    branch: master
    createBranch: true
    directory: /repo1
    repo: https://github.com/[redacted]
    secretRef:
      name: github-pat
  type: git
```
```
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: repo2
  namespace: default
spec:
  content: Package
  deployment: true
  description: Repo2
  git:
    branch: master
    createBranch: true
    directory: /repo2
    repo: https://github.com/[same redacted URL]
    secretRef:
      name: github-pat
  type: git
 ```

I expected to be able to clone a package into either one of these repos:
```
kpt alpha rpkg clone porch-test-blueprints-cd096908f5390cc134a7b4d631cd3717b94b1b5e newpackage --repository repo1 -ndefault
kpt alpha rpkg clone porch-test-blueprints-cd096908f5390cc134a7b4d631cd3717b94b1b5e newpackage --repository repo2 -ndefault
```
### Actual behavior
Though the above is the behavior I'd most prefer (package name independent of the repository), the commands above both produce the error message:
```
Error: Internal error occurred: cannot create newpackage outside of repository directory "repo1"
```

To work around this, I tried including the directory name in the package name. This one worked:
```
kpt alpha rpkg clone porch-test-blueprints-cd096908f5390cc134a7b4d631cd3717b94b1b5e repo1/newpackage --repository repo1 -ndefault
```
However this one:
```
kpt alpha rpkg clone porch-test-blueprints-cd096908f5390cc134a7b4d631cd3717b94b1b5e repo2/newpackage --repository repo2 -ndefault
```
still produces an error message that references the `repo1` directory:
```
Error: Internal error occurred: cannot create repo2/newpackage outside of repository directory "repo1"
```
I was not able to find a way to clone into this second repository.

### Information

kpt version: `1.0.0-beta.19`
porch version: 1de5acf9cc65e99a9b491db2e5dd643c231767b0
porch UI version: https://github.com/GoogleContainerTools/kpt-backstage-plugins/commit/6334354fb4e880ef316ef447609b4f8765dccfa5

### Steps to reproduce the behavior
1. Use Porch UI to register two git repositories with the same repo URL and different directories
2. Attempt to clone a package from a separate blueprint repository (doesn't matter whether it's in the same or a different git repo) into these two Porch repositories
