### ISSUE TITLE
WASM compiled functions don't like non-strings in YAML

### ISSUE THREAD

**Issue by wleese** [kptdev/kpt#3626]
### Expected behavior

Render should succeed regardless of `"123"` or `123` values in yaml.

### Actual behavior

```
Package "numbers":
[RUNNING] WASM "eu.gcr.io/bolcom-stg-bb8-infra-6e4/set-namespace:unstable"
panic: ValueOf: invalid value

goroutine 6 [running]:
syscall/js.ValueOf({0xcb960, 0x119ed80})
	/usr/local/go/src/syscall/js/js.go:208 +0xf7
syscall/js.Value.Set({{}, 0x7ff8000100000012, 0x1140690}, {0x1a8ec8, 0x6}, {0xcb960, 0x119ed80})
	/usr/local/go/src/syscall/js/js.go:303 +0x8
syscall/js.handleEvent()
	/usr/local/go/src/syscall/js/func.go:95 +0x27
[FAIL] "eu.gcr.io/bolcom-stg-bb8-infra-6e4/set-namespace:unstable" in 0s
Error: wrong Node Kind for  expected: MappingNode was ScalarNode: value: {s(<nil>}
```

### Information

kptfile
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: numbers
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: sample description
pipeline:
  mutators:
  - image: eu.gcr.io/xxxx/set-namespace:unstable
    configPath: package-context.yaml
```

set-namespace is compiled to WASM.

package-context.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: example
  namespace: 1234
```

Saw the behavior with `apply-replacements` as well.

### Steps to reproduce the behavior

Use the above resources with a WASM compiled function such as set-namespace.
