### ISSUE TITLE
porch: kpt alpha rpkg get fails when a couple hundred branches

### ISSUE THREAD

**Issue by johnbelamaric** [kptdev/kpt#3882]
### Expected behavior
Valid list of package revisions is returned.

### Actual behavior

```
jbelamaric@jbelamaric:~/proj/tmp/cachingdns-topology$ kpt alpha rpkg get
Error: Get "https://35.192.14.90/apis/porch.kpt.dev/v1alpha1/namespaces/default/packagerevisions": stream error: stream ID 1; INTERNAL_ERROR; received from peer 
jbelamaric@jbelamaric:~/proj/tmp/cachingdns-topology$ k get packagerevisions
Unable to connect to the server: stream error: stream ID 1; INTERNAL_ERROR; received from peer
jbelamaric@jbelamaric:~/proj/tmp/cachingdns-topology$ k get po -n porch-system
NAME                                 READY   STATUS    RESTARTS       AGE
function-runner-77946d6686-jv8kk     1/1     Running   0              5d18h
function-runner-77946d6686-rn57r     1/1     Running   0              5d18h
porch-controllers-5d67bb9fdf-4fs4l   1/1     Running   0              22h
porch-server-78dd559589-qmrvl        1/1     Running   17 (23h ago)   5d
```
### Information
Due to #3877 there are a couple hundred branches after running overnight (see image below).

Porch v0.0.15
kpt v1.0.0-beta.23

![image](https://user-images.githubusercontent.com/9468083/225080436-dfabd9d3-192b-4ad9-9d0f-496d24912d53.png)

### Steps to reproduce the behavior

**Comment by johnbelamaric** [comment]
FYI, I manually deleted all those 200+ branches and now it's working again.

**Comment by johnbelamaric** [comment]
I wonder if it has to do with running on an autopilot cluster with guaranteed pods (not burstable):

```
        name: porch-server
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
```
