### ISSUE TITLE
What RBAC permissions for live apply? Correct values for apiGroups and resources

### ISSUE THREAD

**Issue by WTPascoe** [kptdev/kpt#4095]
I am trying to give a user permissions to do `kpt live apply`

When doing this, an error is returned

> Installing inventory ResourceGroup CRD.
> error: Type ResourceGroup CRD needs update. Please make sure you have the permission to update CRD then run `kpt live install-resource-group`.
> error installing ResourceGroup crd

If I add a far too broad set of rules to their role, this then succeeds. I'd like to understand what permissions are needed to be able to complete the live apply

```
- apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

The file that `live init` has generated and appears to be triggering this error is as follows:

```
resourcegroup.yaml
apiVersion: kpt.dev/v1alpha1
kind: ResourceGroup
metadata:
  name: inventory-27342774
  namespace:  mynamespace
  labels:
    cli-utils.sigs.k8s.io/inventory-id: somenumbershere
```
