### ISSUE TITLE
`kpt fn render` execution adds unintended line comments to manifests

### ISSUE THREAD

**Issue by thombashi** [kptdev/kpt#4211]
`kpt fn render` execution adds unintended line comments to manifests

### Expected behavior
After executing `kpt fn render`, no line comments are added to the manifests unrelated to the `mutators` processing.

### Actual behavior
Each time I execute `kpt fn render`, a copy of the line comments in the manifest unrelated to the processing of `mutators` is added to the manifests.

### Information
Kpt Version: `v1.0.0-beta.57`

### Steps to reproduce the behavior
The reproduction conditions are as follows:

- The manifests contain multiple Kubernetes resources.
- The Kubernetes resources include line comments.
- The `Kptfile`'s `mutators` section contains multiple mutators.
    - As far as I have tested, the issue occurs regardless of the types of mutators.
        - The mutators themselves do not add comments.
    - If there are n mutators, comment lines are added n-1 times.
- Run `kpt fn render`.

When I run `kpt fn render`, some of the comments in the manifest are copied and added to another Kubernetes resource.
This can also occur across files.

Below is a reproduction example. The content is simplified here, but the same phenomenon occurs with manifests generated from the `cert-manager` Helm chart.

#### Example inputs
`Kptfile`:

```yaml
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: Reproduce
info:
  description: Reproduce the issue
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:unstable
      configMap:
        test: "3"
    - image: gcr.io/kpt-fn/apply-setters:unstable
      configMap:
        test: "3"
    - image: gcr.io/kpt-fn/apply-setters:unstable
      configMap:
        test: "3"
```

`a.yaml`:

```yaml
# START A1
kind: Pod
apiVersion: v1
metadata:
  name: dummy A1
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END A1
---
# START A2
kind: Pod
apiVersion: v1
metadata:
  name: dummy A2
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END A2
```

`b.yaml`:

```yaml
# START B1
kind: Pod
apiVersion: v1
metadata:
  name: dummy B1
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END B1
---
# START B2
kind: Pod
apiVersion: v1
metadata:
  name: dummy B2
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END B2
```

#### Example outputs
Unintended line comments are copied and added to the Kubernetes resources.

`a.yaml`:

```yaml
# START A1
kind: Pod
apiVersion: v1
metadata:
  name: dummy A1
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END A1
---
# END A1
# END A1
# START A2
kind: Pod
apiVersion: v1
metadata:
  name: dummy A2
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END A2
```

`b.yaml`:

```yaml
# END A2
# END A2
# START B1
kind: Pod
apiVersion: v1
metadata:
  name: dummy B1
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END B1
---
# END B1
# END B1
# START B2
kind: Pod
apiVersion: v1
metadata:
  name: dummy B2
spec:
  containers:
  - name: nginx
    image: nginx:latest

# END B2
```
