### ISSUE TITLE
Support composing setters -- e.g. project-id sets both project-id and project-name setters

### ISSUE THREAD

**Issue by trodge** [kptdev/kpt#430]
When creating setters for [this project](https://github.com/trodge/cloud-foundation-toolkit/tree/simple-project/config-connector/solutions/projects/kpt/simple-project)

We realized that we wanted a way to set project-name independently of project-id, while keeping a project-id setter which will set both the spec.name and the metadata.name to the same value.

Currently I do not think there is a way to do this short of having the user of the package edit project.yaml manually.

**Comment by morgante** [comment]
To elaborate further, the ideal behavior we'd like to see

1. `kpt cfg set . project-id test` sets both project-id and project-name to test
2. `kpy cfg set . project-name testName` overrides the project-name to `testName` (while leaving project-id untouched)

**Comment by mortent** [comment]
Here is a first draft on a proposal for how we could add support for composite setters in kpt. It does not fully follow the request in this issue, in particular it requires a composite setter to only reference existing setters and does not allow it to have an overlapping name with any of them.

Command: 
```
kpt cfg create-composed-setter <DIR> <name> <setter>... [--type] [--description] [--schema-path]
```
Requirements:
* name must be unique, so can't overlap with existing setters or substitutions
* All listed setters must exist
* A composite setter does not have a value.
* A composite setter can set values on setters even if those does not currently have the same value.
* If a type is provided, all of the setters included must share the same type.
* The schema for the setter will be the union ([allOf](https://json-schema.org/understanding-json-schema/reference/combining.html#allof)) of the optional schema for the composite setter and the schema for all included setters.
  * If possible, we should verify when creating the setter that at least one value exists that would satisfy the combined schema. Not sure how easy it is to achieve this.

Consequences for list-setters
* composite setters will use the following fields when listed: name, description, setters, count
* setters will list the name of the setters covered by the composite setter
* count includes the sum of the count value of all the covered setters.

Example Kptfile:
```
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
  name: simple-project
packageMetadata:
  shortDescription: A simple project
openAPI:
  definitions:
    io.k8s.cli.compositesetter.port:
      description: port for database
      x-k8s-cli:
        setter:
          name: port
          setters:
          - host-port
          - db-port
    io.k8s.cli.setters.host-port:
      description: the port on which the database should be listening for requests
      x-k8s-cli:
        setter:
          name: host-port
          value: 3306
    io.k8s.cli.setters.db-port:
      description: the port which the application should use for calls to the database
      x-k8s-cli:
        setter:
          name: db-port
          value: 3306
```

@phanimarupaka @frankfarzan @jijiew

**Comment by phanimarupaka** [comment]
@mortent From the first look, it looks good and addresses the problem in context. But thinking of the broader picture, we are introducing a new concept as a whole which is Composite Setter. For a newbie to kpt, substitutions are itself [confusing](https://www.reddit.com/r/kubernetes/comments/ft9yod/kpt_packaging_up_your_kubernetes_configuration/) and it is easy for people to mistake substitutions with composite setters as in theory they both are group of setters. Let me know your thoughts. 

Open questions:
1. How does this composite setters work with substitutions.
2. The main advantage here is to set group of setters with same value, can we address this by accepting multiple setters to be set with single command?
`kpt cfg set port-setter1,port-setter2... 8080`

**Comment by FrenchBen** [comment]
Along the regex lines, it would be nice to have that support in substitution patterns, say for when multiple images share the same tag. 
```
...
image: gcr.io/google-samples/gb-frontend:v4
...
image: gcr.io/google-samples/gb-backend:v4
...
```
```
# Kptfile -- updated
openAPI:
  definitions:
    io.k8s.cli.setters.TAG_SETTER:
      x-k8s-cli:
        setter:
          name: TAG_SETTER
          value: v4
    io.k8s.cli.substitutions.image-value:
      x-k8s-cli:
        substitution:
          name: image-value
          pattern: gcr.io/google-samples/gb-(frontend|backend):${TAG_SETTER}
          values:
          - marker: ${TAG_SETTER}
            ref: '#/definitions/io.k8s.cli.setters.TAG_SETTER'
```
